"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, Bike, CalendarDays, ChevronRight, CircleDollarSign, ExternalLink, Gauge, LayoutDashboard, Loader2, LogOut, MessageCircle, Plus, Search, Target, TrendingUp, Users } from "lucide-react";
import type { Lead, Motorcycle } from "@/lib/demo-data";
import { demoAds, demoGoal, demoLeads, parseImages } from "@/lib/demo-data";
import { catalogMotorcycles } from "@/lib/catalog-data";
import CatalogImage from "@/components/catalog-image";
import { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";

type View="painel"|"estoque"|"clientes"|"agenda"|"metas"|"relatorios";
type Goal=typeof demoGoal; type Ad=(typeof demoAds)[number];
const currency=(n:number|null|undefined)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(n||0);
const daysInStock=(m:Motorcycle)=>Math.max(0,Math.floor((Date.now()-new Date(m.acquiredAt).getTime())/86400000));
const stages=[{id:"novo",label:"Lead novo",color:"#4ea1ff"},{id:"negociando",label:"Negociando",color:"#f0b429"},{id:"visita",label:"Visita marcada",color:"#a78bfa"},{id:"retorno",label:"Ligar de volta",color:"#fb7185"},{id:"vendido",label:"Vendido",color:"#63d49b"}];

export default function CrmDashboard({displayName}:{displayName:string}){
  const [view,setView]=useState<View>("painel"),[motos,setMotos]=useState<Motorcycle[]>(catalogMotorcycles),[contacts,setContacts]=useState<Lead[]>(demoLeads),[goal,setGoal]=useState<Goal>(demoGoal),[ads,setAds]=useState<Ad[]>(demoAds),[demo,setDemo]=useState(true),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[notice,setNotice]=useState("");
  const [motoDialog,setMotoDialog]=useState(false),[leadDialog,setLeadDialog]=useState(false);
  useEffect(()=>{fetch("/api/crm").then(r=>r.ok?r.json():Promise.reject()).then(d=>{setMotos(d.motorcycles);setContacts(d.leads);setGoal(d.goal);setAds(d.ads);setDemo(d.demo)}).catch(()=>setNotice("Modo de apresentação ativo.")).finally(()=>setLoading(false))},[]);
  const sold=useMemo(()=>motos.filter(m=>m.status==="vendida"),[motos]),available=motos.filter(m=>m.status==="disponivel"),revenue=sold.reduce((s,m)=>s+(m.salePrice||0),0),profit=sold.reduce((s,m)=>s+Math.max(0,(m.salePrice||0)-(m.purchasePrice||0)),0),inventoryValue=available.filter(m=>m.ownership==="propria").reduce((s,m)=>s+(m.purchasePrice||0),0),targetPct=Math.min(100,Math.round(sold.length/Math.max(1,goal.salesTarget)*100));
  const title={painel:"Visão geral",estoque:"Estoque",clientes:"CRM de clientes",agenda:"Agenda",metas:"Metas",relatorios:"Relatórios"}[view];
  const post=async(payload:Record<string,unknown>)=>{const r=await fetch("/api/crm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível salvar");return d};
  const moveLead=async(id:number,stage:string)=>{setContacts(c=>c.map(l=>l.id===id?{...l,stage,updatedAt:new Date().toISOString()}:l));try{await post({action:"move_lead",id,stage});setNotice("Etapa atualizada.")}catch(e){setNotice(e instanceof Error?e.message:"Erro ao atualizar")}};
  return <SidebarProvider><div className="crm-root">
    <Sidebar collapsible="offcanvas" className="crm-sidebar"><SidebarHeader><div className="crm-brand"><span>LM</span><div><strong>LUAN MOTOS</strong><small>Central comercial</small></div></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupContent><SidebarMenu>{[
      ["painel",LayoutDashboard,"Painel"],["estoque",Bike,"Estoque"],["clientes",Users,"Clientes"],["agenda",CalendarDays,"Agenda"],["metas",Target,"Metas"],["relatorios",BarChart3,"Relatórios"]
    ].map(([id,Icon,label])=><SidebarMenuItem key={String(id)}><SidebarMenuButton isActive={view===id} onClick={()=>setView(id as View)}><Icon/><span>{String(label)}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter><a className="site-preview-link" href="/" target="_blank">Ver site público <ExternalLink/></a><a className="site-preview-link" href="/signout-with-chatgpt?return_to=/"><LogOut/> Sair</a></SidebarFooter></Sidebar>
    <SidebarInset className="crm-main"><header className="crm-topbar"><div className="topbar-title"><SidebarTrigger/><div><span>Central comercial</span><h1>{title}</h1></div></div><div className="topbar-actions"><div className="crm-search"><Search/><input aria-label="Buscar" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente ou moto"/></div><div className="user-chip"><span>{displayName.slice(0,1).toUpperCase()}</span><div><strong>{displayName.split("@")[0]}</strong><small>Administrador</small></div></div></div></header>
    {notice&&<button className="notice" onClick={()=>setNotice("")}>{notice}<span>×</span></button>}{demo&&<div className="demo-banner"><strong>Apresentação ativa</strong><span>Os dados abaixo ilustram o sistema. Ao cadastrar a primeira moto ou cliente, o banco real assume o controle.</span></div>}
    <div className="crm-content">{loading?<div className="crm-loading"><Loader2/> Carregando operação...</div>:<>
      {view==="painel"&&<DashboardView motos={motos} contacts={contacts} goal={goal} revenue={revenue} profit={profit} inventoryValue={inventoryValue} targetPct={targetPct} onView={setView}/>} 
      {view==="estoque"&&<InventoryView motos={motos} query={query} onAdd={()=>setMotoDialog(true)} onUpdate={async(id,updates)=>{setMotos(v=>v.map(m=>m.id===id?{...m,...updates}:m));try{await post({action:"update_motorcycle",id,...updates});setNotice("Estoque e site atualizados.")}catch(e){setNotice(e instanceof Error?e.message:"Erro")}}}/>} 
      {view==="clientes"&&<ClientsView motos={motos} contacts={contacts} query={query} onAdd={()=>setLeadDialog(true)} onMove={moveLead}/>} 
      {view==="agenda"&&<AgendaView contacts={contacts} motos={motos}/>} 
      {view==="metas"&&<GoalsView goal={goal} sold={sold.length} revenue={revenue} profit={profit} onSave={async(next)=>{setGoal(next);try{await post({action:"save_goal",...next});setNotice("Meta atualizada.")}catch(e){setNotice(e instanceof Error?e.message:"Erro")}}}/>} 
      {view==="relatorios"&&<ReportsView ads={ads} revenue={revenue} profit={profit} sold={sold.length}/>} 
    </>}</div></SidebarInset>
    <AddMotorcycleDialog open={motoDialog} onOpenChange={setMotoDialog} onSave={async p=>{try{const d=await post({action:"add_motorcycle",...p});setMotos(v=>demo?[d.motorcycle]:[d.motorcycle,...v]);setDemo(false);setMotoDialog(false);setNotice("Moto publicada no estoque e no site.")}catch(e){setNotice(e instanceof Error?e.message:"Erro")}}}/>
    <AddLeadDialog open={leadDialog} onOpenChange={setLeadDialog} motos={motos} onSave={async p=>{try{const d=await post({action:"add_lead",...p});setContacts(v=>demo?[d.lead]:[d.lead,...v]);setDemo(false);setLeadDialog(false);setNotice("Cliente registrado no CRM.")}catch(e){setNotice(e instanceof Error?e.message:"Erro")}}}/>
  </div></SidebarProvider>
}

function DashboardView({motos,contacts,goal,revenue,profit,inventoryValue,targetPct,onView}:{motos:Motorcycle[];contacts:Lead[];goal:Goal;revenue:number;profit:number;inventoryValue:number;targetPct:number;onView:(v:View)=>void}){
 const sold=motos.filter(m=>m.status==="vendida").length,missingPrice=motos.filter(m=>m.status==="disponivel"&&!m.askingPrice),old=[...motos.filter(m=>m.status==="disponivel")].sort((a,b)=>daysInStock(b)-daysInStock(a)).slice(0,4);
 return <><section className="welcome-row"><div><p>Olá, Luan.</p><h2>A operação inteira,<br/><em>sem achismo.</em></h2></div><div className="goal-orbit"><div><span>{targetPct}%</span><small>da meta</small></div><Progress value={targetPct}/><p>{sold} de {goal.salesTarget} motos vendidas</p></div></section>
 <section className="metric-grid"><Metric icon={Bike} label="Estoque disponível" value={String(motos.filter(m=>m.status==="disponivel").length)} detail={`${motos.filter(m=>m.ownership==="consignada"&&m.status==="disponivel").length} consignadas`}/><Metric icon={CircleDollarSign} label="Valor próprio em estoque" value={currency(inventoryValue)} detail="Consignadas não entram na conta"/><Metric icon={TrendingUp} label="Faturamento" value={currency(revenue)} detail={`${sold} vendas registradas`}/><Metric icon={Gauge} label="Lucro realizado" value={currency(profit)} detail="Margem apurada nas vendas"/></section>
 <section className="dashboard-grid"><div className="panel"><div className="panel-head"><div><span>Prioridade comercial</span><h3>Estoque parado há mais tempo</h3></div><button onClick={()=>onView("estoque")}>Ver estoque <ChevronRight/></button></div><div className="aging-list">{old.map(m=><div key={m.id}><CatalogImage width={58} height={48} src={parseImages(m.images)[0]||"/images/showroom.jpg"} alt=""/><div><strong>{m.brand} {m.model}</strong><span>{m.year||"Ano não informado"}</span></div><b className={daysInStock(m)>60?"danger":""}>{daysInStock(m)} dias</b></div>)}</div></div>
 <div className="panel attention-panel"><div className="panel-head"><div><span>Pendências</span><h3>O que trava a venda</h3></div></div><button onClick={()=>onView("estoque")}><b>{missingPrice.length}</b><span>Motos sem preço publicado<small>Defina a condição para liberar no site.</small></span><ChevronRight/></button><button onClick={()=>onView("estoque")}><b>{motos.filter(m=>m.status==="disponivel"&&!m.minimumPrice).length}</b><span>Sem desconto liberado<small>Defina o preço mínimo de negociação.</small></span><ChevronRight/></button><button onClick={()=>onView("clientes")}><b>{contacts.filter(l=>l.stage!=="vendido").length}</b><span>Negociações em andamento<small>Veja quem precisa de retorno hoje.</small></span><ChevronRight/></button></div></section>
 <section className="panel"><div className="panel-head"><div><span>Pipeline</span><h3>Clientes por etapa</h3></div><button onClick={()=>onView("clientes")}>Abrir CRM <ChevronRight/></button></div><div className="pipeline-summary">{stages.map(s=><div key={s.id}><i style={{background:s.color}}/><strong>{contacts.filter(l=>l.stage===s.id).length}</strong><span>{s.label}</span></div>)}</div></section></>
}
function Metric({icon:Icon,label,value,detail}:{icon:typeof Bike;label:string;value:string;detail:string}){return <article className="metric-card"><div className="metric-icon"><Icon/></div><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}

function InventoryView({motos,query,onAdd,onUpdate}:{motos:Motorcycle[];query:string;onAdd:()=>void;onUpdate:(id:number,u:Partial<Motorcycle>)=>void}){const rows=motos.filter(m=>`${m.brand} ${m.model}`.toLowerCase().includes(query.toLowerCase()));return <section><div className="view-intro"><div><p>{rows.filter(m=>m.status==="disponivel").length} motos disponíveis</p><h2>Controle de estoque e margem.</h2></div><button className="crm-primary" onClick={onAdd}><Plus/> Adicionar moto</button></div><div className="inventory-table"><div className="inventory-row table-head"><span>Moto</span><span>Entrada</span><span>Margem</span><span>Preço anunciado</span><span>Status</span><span>Ações</span></div>{rows.map(m=><div className="inventory-row" key={m.id}><div className="inventory-bike"><CatalogImage width={72} height={54} src={parseImages(m.images)[0]||"/images/showroom.jpg"} alt=""/><div><strong>{m.brand} {m.model}</strong><small>{m.year||"Ano não informado"} · {m.ownership}</small></div></div><span>{daysInStock(m)} dias</span><span>{m.minimumPrice&&m.purchasePrice?currency(m.minimumPrice-m.purchasePrice):"Definir"}</span><span>{m.askingPrice?currency(m.askingPrice):<b className="warning">Sem preço</b>}</span><select value={m.status} onChange={e=>{const status=e.target.value;if(status==="vendida"){const value=window.prompt("Valor final da venda",String(m.askingPrice||""));if(value===null)return;onUpdate(m.id,{status,salePrice:Number(value),published:false})}else onUpdate(m.id,{status})}}><option value="disponivel">Disponível</option><option value="reservada">Reservada</option><option value="vendida">Vendida</option></select><div className="row-actions"><button title="Publicar/ocultar" onClick={()=>onUpdate(m.id,{published:!m.published})}>{m.published?"No site":"Oculta"}</button><a title="Abrir no WhatsApp" href={`https://wa.me/558399036083?text=${encodeURIComponent(`Olá! Tenho interesse na ${m.brand} ${m.model}.`)}`} target="_blank"><MessageCircle/></a></div></div>)}</div></section>}

function ClientsView({motos,contacts,query,onAdd,onMove}:{motos:Motorcycle[];contacts:Lead[];query:string;onAdd:()=>void;onMove:(id:number,s:string)=>void}){const filtered=contacts.filter(l=>l.name.toLowerCase().includes(query.toLowerCase()));return <section><div className="view-intro"><div><p>{contacts.filter(l=>l.stage!=="vendido").length} oportunidades abertas</p><h2>Nenhum cliente esquecido.</h2></div><button className="crm-primary" onClick={onAdd}><Plus/> Registrar cliente</button></div><div className="kanban">{stages.map(stage=><div className="kanban-column" key={stage.id} onDragOver={e=>e.preventDefault()} onDrop={e=>onMove(Number(e.dataTransfer.getData("lead")),stage.id)}><div className="kanban-head"><i style={{background:stage.color}}/><strong>{stage.label}</strong><span>{filtered.filter(l=>l.stage===stage.id).length}</span></div>{filtered.filter(l=>l.stage===stage.id).map(lead=>{const moto=motos.find(m=>m.id===lead.motorcycleId);return <article className="lead-card" draggable onDragStart={e=>e.dataTransfer.setData("lead",String(lead.id))} key={lead.id}><div className="lead-top"><span>{lead.name.slice(0,1)}</span><div><strong>{lead.name}</strong><small>{lead.source}</small></div></div>{moto&&<p><Bike/> {moto.brand} {moto.model}</p>}<p className="lead-note">{lead.notes||"Sem observações"}</p><div className="lead-footer"><span>{lead.followUpAt?new Date(lead.followUpAt).toLocaleDateString("pt-BR",{day:"2-digit",month:"short"}):"Sem retorno"}</span><a href={`https://wa.me/${lead.phone}?text=${encodeURIComponent(`Olá, ${lead.name.split(" ")[0]}! Aqui é da Luan Motos.`)}`} target="_blank"><MessageCircle/></a></div><select aria-label="Mover etapa" value={lead.stage} onChange={e=>onMove(lead.id,e.target.value)}>{stages.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></article>})}</div>)}</div></section>}

function AgendaView({contacts,motos}:{contacts:Lead[];motos:Motorcycle[]}){const events=contacts.filter(l=>l.followUpAt).sort((a,b)=>new Date(a.followUpAt!).getTime()-new Date(b.followUpAt!).getTime());return <section><div className="view-intro"><div><p>Próximos compromissos</p><h2>Follow-up no tempo certo.</h2></div></div><div className="agenda-layout"><div className="agenda-date"><strong>{new Date().getDate()}</strong><span>{new Date().toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</span></div><div className="agenda-list">{events.map(e=>{const m=motos.find(x=>x.id===e.motorcycleId);return <article key={e.id}><time>{new Date(e.followUpAt!).toLocaleDateString("pt-BR",{weekday:"short",day:"2-digit",month:"short"})}</time><i/><div><strong>{e.stage==="visita"?"Visita marcada":"Retorno comercial"} · {e.name}</strong><span>{m?`${m.brand} ${m.model}`:"Interesse ainda não definido"}</span><small>{e.notes}</small></div><a href={`https://wa.me/${e.phone}`} target="_blank"><MessageCircle/></a></article>})}</div></div></section>}

function GoalsView({goal,sold,revenue,profit,onSave}:{goal:Goal;sold:number;revenue:number;profit:number;onSave:(g:Goal)=>void}){const [draft,setDraft]=useState(goal);return <section><div className="view-intro"><div><p>{goal.month}</p><h2>Meta visível. Time em movimento.</h2></div><button className="crm-primary" onClick={()=>onSave(draft)}>Salvar metas</button></div><div className="goal-cards">{[{label:"Motos vendidas",actual:sold,target:draft.salesTarget,key:"salesTarget"},{label:"Faturamento",actual:revenue,target:draft.revenueTarget,key:"revenueTarget"},{label:"Lucro",actual:profit,target:draft.profitTarget,key:"profitTarget"}].map((g,i)=>{const pct=Math.min(100,Math.round(g.actual/Math.max(1,g.target)*100));return <article key={g.key}><span>{g.label}</span><strong>{i?currency(g.actual):g.actual}</strong><Progress value={pct}/><p>{pct}% da meta</p><label>Meta do mês<input type="number" value={g.target} onChange={e=>setDraft({...draft,[g.key]:Number(e.target.value)})}/></label></article>})}</div></section>}

function ReportsView({ads,revenue,profit,sold}:{ads:Ad[];revenue:number;profit:number;sold:number}){
  const investment=ads.reduce((sum,item)=>sum+item.investment,0);
  const leadCount=ads.reduce((sum,item)=>sum+item.leads,0);
  const roi=investment?((profit-investment)/investment)*100:0;
  const costPerLead=leadCount?currency(investment/leadCount):"R$ 0";
  const maxLeads=Math.max(...ads.map(item=>item.leads),1);
  return <section>
    <div className="view-intro"><div><p>Mídia + vendas</p><h2>O tráfego ligado ao caixa.</h2></div></div>
    <div className="report-metrics"><Metric icon={CircleDollarSign} label="Investimento" value={currency(investment)} detail="Google e Meta"/><Metric icon={Users} label="Leads" value={String(leadCount)} detail={costPerLead+" por lead"}/><Metric icon={Bike} label="Vendas" value={String(sold)} detail={currency(revenue)}/><Metric icon={TrendingUp} label="ROI sobre lucro" value={roi.toFixed(1)+"%"} detail={currency(profit)+" de lucro"}/></div>
    <div className="panel ad-panel"><div className="panel-head"><div><span>Desempenho por canal</span><h3>Onde o dinheiro está voltando</h3></div></div>{ads.map(item=><div className="ad-row" key={item.id}><strong>{item.channel}</strong><div><i style={{width:(item.leads/maxLeads*100)+"%"}}/></div><span>{item.leads} leads</span><span>{currency(item.investment)}</span><b>{item.sales} vendas</b></div>)}</div>
  </section>;
}

function AddMotorcycleDialog({open,onOpenChange,onSave}:{open:boolean;onOpenChange:(o:boolean)=>void;onSave:(p:Record<string,unknown>)=>void}){const [form,setForm]=useState<Record<string,string>>({brand:"",model:"",year:String(new Date().getFullYear()),mileage:"0",version:"",engine:"",color:"",askingPrice:"",purchasePrice:"",minimumPrice:"",ownership:"propria",description:""}),[file,setFile]=useState<File|null>(null),[saving,setSaving]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);let images:string[]=[];if(file){const fd=new FormData();fd.append("file",file);const r=await fetch("/api/upload",{method:"POST",body:fd});if(r.ok)images=[(await r.json()).url]}await onSave({...form,images});setSaving(false)};return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="crm-dialog"><DialogHeader><DialogTitle>Adicionar moto</DialogTitle><DialogDescription>Ao salvar, ela entra no estoque e aparece no site público.</DialogDescription></DialogHeader><form onSubmit={submit} className="crm-form"><div className="form-grid"><Field label="Marca"><input required value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}/></Field><Field label="Modelo"><input required value={form.model} onChange={e=>setForm({...form,model:e.target.value})}/></Field><Field label="Versão"><input value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/></Field><Field label="Ano"><input type="number" value={form.year} onChange={e=>setForm({...form,year:e.target.value})}/></Field><Field label="Quilometragem"><input type="number" value={form.mileage} onChange={e=>setForm({...form,mileage:e.target.value})}/></Field><Field label="Cilindrada"><input placeholder="Ex.: 300 cc" value={form.engine} onChange={e=>setForm({...form,engine:e.target.value})}/></Field><Field label="Preço anunciado"><input type="number" value={form.askingPrice} onChange={e=>setForm({...form,askingPrice:e.target.value})}/></Field><Field label="Preço mínimo"><input type="number" value={form.minimumPrice} onChange={e=>setForm({...form,minimumPrice:e.target.value})}/></Field><Field label="Custo / repasse"><input type="number" value={form.purchasePrice} onChange={e=>setForm({...form,purchasePrice:e.target.value})}/></Field><Field label="Tipo"><select value={form.ownership} onChange={e=>setForm({...form,ownership:e.target.value})}><option value="propria">Própria</option><option value="consignada">Consignada</option></select></Field></div><Field label="Descrição"><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="Foto principal"><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></Field><button className="crm-primary" disabled={saving}>{saving?<Loader2 className="spin"/>:<Plus/>}{saving?"Publicando...":"Adicionar ao estoque"}</button></form></DialogContent></Dialog>}

function AddLeadDialog({open,onOpenChange,motos,onSave}:{open:boolean;onOpenChange:(o:boolean)=>void;motos:Motorcycle[];onSave:(p:Record<string,unknown>)=>void}){const [form,setForm]=useState({name:"",phone:"",source:"WhatsApp",motorcycleId:"",stage:"novo",notes:"",followUpAt:""});return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="crm-dialog"><DialogHeader><DialogTitle>Registrar cliente</DialogTitle><DialogDescription>Associe o interesse e defina o próximo passo.</DialogDescription></DialogHeader><form className="crm-form" onSubmit={e=>{e.preventDefault();onSave(form)}}><div className="form-grid"><Field label="Nome"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="WhatsApp"><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Origem"><select value={form.source} onChange={e=>setForm({...form,source:e.target.value})}><option>WhatsApp</option><option>Site</option><option>Instagram</option><option>Google Ads</option><option>Indicação</option></select></Field><Field label="Moto de interesse"><select value={form.motorcycleId} onChange={e=>setForm({...form,motorcycleId:e.target.value})}><option value="">Ainda não definida</option>{motos.filter(m=>m.status==="disponivel").map(m=><option key={m.id} value={m.id}>{m.brand} {m.model}</option>)}</select></Field><Field label="Etapa"><select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})}>{stages.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></Field><Field label="Próximo contato"><input type="datetime-local" value={form.followUpAt} onChange={e=>setForm({...form,followUpAt:e.target.value})}/></Field></div><Field label="Observações"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><button className="crm-primary"><Plus/> Registrar no CRM</button></form></DialogContent></Dialog>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="form-field"><span>{label}</span>{children}</label>}
