export type Motorcycle = { id:number; slug:string; brand:string; model:string; version:string; year:number; mileage:number; engine:string; color:string; askingPrice:number|null; purchasePrice:number|null; minimumPrice:number|null; salePrice:number|null; ownership:string; status:string; featured:boolean; published:boolean; description:string; features:string; images:string; acquiredAt:string; soldAt:string|null; createdAt:string; updatedAt:string };
export type Lead = { id:number; name:string; phone:string; email:string; source:string; motorcycleId:number|null; stage:string; notes:string; followUpAt:string|null; saleValue:number|null; profit:number|null; createdAt:string; updatedAt:string };

const now = new Date();
const ago = (days:number) => new Date(now.getTime()-days*86400000).toISOString();
const ahead = (days:number) => new Date(now.getTime()+days*86400000).toISOString();
export const demoMotorcycles: Motorcycle[] = [
  {id:1,slug:"yamaha-xsr-700-2024",brand:"Yamaha",model:"XSR 700",version:"ABS",year:2024,mileage:8200,engine:"689 cc",color:"Prata",askingPrice:46900,purchasePrice:40500,minimumPrice:44400,salePrice:null,ownership:"propria",status:"disponivel",featured:true,published:true,description:"Visual clássico, motor bicilíndrico e torque para transformar qualquer trajeto.",features:'["ABS","Chave reserva","Revisada"]',images:'["/images/yamaha.jpg"]',acquiredAt:ago(18),soldAt:null,createdAt:ago(18),updatedAt:ago(1)},
  {id:2,slug:"honda-cb-500f-2023",brand:"Honda",model:"CB 500F",version:"ABS",year:2023,mileage:11400,engine:"471 cc",color:"Grafite",askingPrice:39900,purchasePrice:35100,minimumPrice:37800,salePrice:null,ownership:"consignada",status:"disponivel",featured:true,published:true,description:"Equilíbrio entre esportividade, conforto e confiança para cidade ou estrada.",features:'["ABS","Manual","Pneus novos"]',images:'["/images/showroom.jpg"]',acquiredAt:ago(43),soldAt:null,createdAt:ago(43),updatedAt:ago(3)},
  {id:3,slug:"yamaha-lander-250-2024",brand:"Yamaha",model:"Lander 250",version:"Connected",year:2024,mileage:8151,engine:"249 cc",color:"Azul",askingPrice:29490,purchasePrice:25500,minimumPrice:27900,salePrice:null,ownership:"consignada",status:"disponivel",featured:false,published:true,description:"Pronta para o uso diário e para sair do asfalto quando o caminho pedir.",features:'["ABS","Painel digital","Revisada"]',images:'["/images/showroom.jpg"]',acquiredAt:ago(67),soldAt:null,createdAt:ago(67),updatedAt:ago(2)},
  {id:4,slug:"kawasaki-z300-2022",brand:"Kawasaki",model:"Z300",version:"ABS",year:2022,mileage:17800,engine:"296 cc",color:"Vermelha",askingPrice:25800,purchasePrice:21800,minimumPrice:24200,salePrice:25500,ownership:"propria",status:"vendida",featured:false,published:false,description:"Naked compacta, ágil e com presença esportiva.",features:"[]",images:'["/images/showroom.jpg"]',acquiredAt:ago(35),soldAt:ago(3),createdAt:ago(35),updatedAt:ago(3)},
];
export const demoLeads: Lead[] = [
  {id:1,name:"Rafael Lima",phone:"5583991112233",email:"",source:"Site",motorcycleId:1,stage:"novo",notes:"Pediu mais fotos pelo site.",followUpAt:ahead(1),saleValue:null,profit:null,createdAt:ago(0),updatedAt:ago(0)},
  {id:2,name:"Camila Alves",phone:"5583992223344",email:"",source:"Instagram",motorcycleId:2,stage:"negociando",notes:"Tem uma Fazer na troca.",followUpAt:ahead(2),saleValue:null,profit:null,createdAt:ago(4),updatedAt:ago(1)},
  {id:3,name:"Bruno Santos",phone:"5583993334455",email:"",source:"WhatsApp",motorcycleId:3,stage:"visita",notes:"Visita sábado, 10h.",followUpAt:ahead(3),saleValue:null,profit:null,createdAt:ago(6),updatedAt:ago(1)},
  {id:4,name:"João Pedro",phone:"5583994445566",email:"",source:"Indicação",motorcycleId:2,stage:"retorno",notes:"Ligar após análise do financiamento.",followUpAt:ahead(1),saleValue:null,profit:null,createdAt:ago(8),updatedAt:ago(2)},
  {id:5,name:"Fabyny Costa",phone:"5583995556677",email:"",source:"Instagram",motorcycleId:4,stage:"vendido",notes:"Entrega concluída.",followUpAt:null,saleValue:25500,profit:3700,createdAt:ago(19),updatedAt:ago(3)},
];
export const demoGoal = {id:1,month:now.toISOString().slice(0,7),salesTarget:5,revenueTarget:150000,profitTarget:22000};
export const demoAds = [{id:1,month:now.toISOString().slice(0,7),channel:"Google Ads",investment:1280,leads:24,sales:1,revenue:25500,profit:3700},{id:2,month:now.toISOString().slice(0,7),channel:"Meta Ads",investment:860,leads:31,sales:0,revenue:0,profit:0}];
export function parseImages(value:string|null|undefined){try{const parsed=JSON.parse(value||"[]");return Array.isArray(parsed)?parsed:[]}catch{return []}}
